.catch(_ => {
  // Error handling here
}); 